### ISSUE TITLE
JS: FizzBuzzを作ってください。

### ISSUE THREAD

**Issue by uugo-yuji** [uugo-yuji/HasimotoSan#1]
ファイル等は私 @uugo-yuji が用意します。
ブランチを必ず切って処理を書いてください。
細かくコミットして頂いて構いません。
動作確認を必ず行なってください。
@Hashimoto-Noriaki

**Comment by Hashimoto-Noriaki** [comment]
@uugo-yuji さん1点質問です。
VScodeをHasimotoSanで開きたいと思っています。
ターミナルで cd ~/Hashimotosanで開こうと思ったのですが
開くことができなかったです。

VScodeで作業の方法がわからないです。どう対応すればいいでしょうか。
もしくはGitHub上で作業するのでしょうか。
上の2点を踏まえてご教授お願いします。
ご教授お願いします。

**Comment by uugo-yuji** [comment]
@Hashimoto-Noriaki さん

こちらの記事に対処方があるので一度、読んで見てください。
わからない事や単語など出来るだけ自分で調べて対処してみましょう！
https://qiita.com/ki_shi_0922/items/988c9da48e9266665503

これでもわからなければ再度、言ってください。

**Comment by Hashimoto-Noriaki** [comment]
@uugo-yuji さん
進捗報告です。
FizzBuzz問題を作成しました。
これからリポジトリをクローンします。

**Comment by Hashimoto-Noriaki** [comment]
@uugo-yuji 
1点質問です。
JavaScriptのmain.jsとindex.htmlを連携させようと思っています。
しかし以下のエラーにより連携ができない状況です。

``
GET http://127.0.0.1:5501/javascript/main.js net::ERR_ABORTED 404 (Not Found)
``
404つまりmain.jsが見つからないという状況になっています。

⚫︎試したこと　仮説

1. まずindex.htmlの中のbodyタグに<script src="./javascript/main.js"></script>を記述しました。

``index.html
<body>
    <script src="./javascript/main.js"></script>
  </body>
``

これで動くと思いましたが、上記のようなエラーが出てしまっています。



2. 次にこの記事を参考にしました。

https://qiita.com/AkiYanagimoto/items/491518156e85abffc918

JSファイルの置き場所ファイルを作成して読み込む場合は、public/jsの下に配置とありましたが
publicを作らずとも動くと思ったが動きませんでした。


ご教授お願いします。

**Comment by Hashimoto-Noriaki** [comment]
@uugo-yujiさん
PRを出しました。ご確認お願いします。

https://github.com/uugo-yuji/HasimotoSan/pull/2
